from __future__ import annotations

from ._version import __version__
from .analysis import (
    compute_pathway_activity_matrix,
    ligand_receptor_topology_analysis,
    pathway_topology_analysis,
)
from .datasets import PUBLIC_DATASET_SOURCES, get_public_dataset_sources
from .io import (
    XeniumSData,
    load_anndata_from_partial,
    load_xenium_gene_protein,
    read_sdata,
    read_xenium,
    write_xenium,
)
from .multimodal import (
    ProteinMicroEnv,
    ProteinModelResult,
    aggregate_multi_sample_study,
    annotate_joint_cell_states,
    build_cohort_handoff_spec,
    build_panel_gap_table,
    build_serializable_pilot_summary,
    build_spatial_niches,
    build_summary,
    build_top_hypotheses_table,
    compute_rna_protein_discordance,
    extract_ranked_patches,
    load_rna_protein_anndata,
    plot_auc_heatmap,
    plot_DE_volcano,
    plot_model_diagnostics,
    plot_topk_per_cluster,
    protein_gene_correlation,
    render_markdown_report,
    render_renal_immune_resistance_report,
    rna_protein_cluster_analysis,
    run_renal_immune_resistance_pilot,
    run_validated_renal_ffpe_smoke,
    score_immune_resistance_program,
    validate_summary,
    write_model_scores,
    write_output_artifacts,
    write_renal_immune_resistance_artifacts,
)

__all__ = [
    "__version__",
    "PUBLIC_DATASET_SOURCES",
    "ProteinMicroEnv",
    "ProteinModelResult",
    "XeniumSData",
    "aggregate_multi_sample_study",
    "annotate_joint_cell_states",
    "build_cohort_handoff_spec",
    "build_panel_gap_table",
    "build_serializable_pilot_summary",
    "build_spatial_niches",
    "build_summary",
    "build_top_hypotheses_table",
    "compute_pathway_activity_matrix",
    "compute_rna_protein_discordance",
    "extract_ranked_patches",
    "get_public_dataset_sources",
    "ligand_receptor_topology_analysis",
    "load_anndata_from_partial",
    "load_rna_protein_anndata",
    "load_xenium_gene_protein",
    "pathway_topology_analysis",
    "plot_auc_heatmap",
    "plot_DE_volcano",
    "plot_model_diagnostics",
    "plot_topk_per_cluster",
    "protein_gene_correlation",
    "read_sdata",
    "read_xenium",
    "render_markdown_report",
    "render_renal_immune_resistance_report",
    "rna_protein_cluster_analysis",
    "run_renal_immune_resistance_pilot",
    "run_validated_renal_ffpe_smoke",
    "score_immune_resistance_program",
    "validate_summary",
    "write_model_scores",
    "write_output_artifacts",
    "write_renal_immune_resistance_artifacts",
    "write_xenium",
]
