from __future__ import annotations

from importlib import import_module

from ._version import __version__

_MODULE_EXPORTS = {
    "benchmarking": ".benchmarking",
    "contour": ".contour",
    "gmi": ".gmi",
    "io": ".io",
    "cci": ".cci",
    "mechanostress": ".mechanostress",
    "multimodal": ".multimodal",
    "pathway": ".pathway",
    "perturb": ".perturb",
    "validation": ".validation",
}

_ATTRIBUTE_EXPORTS = {
    "PUBLIC_DATASET_SOURCES": (".datasets", "PUBLIC_DATASET_SOURCES"),
    "get_public_dataset_sources": (".datasets", "get_public_dataset_sources"),
    "ProteinMicroEnv": (".multimodal", "ProteinMicroEnv"),
    "ProteinModelResult": (".multimodal", "ProteinModelResult"),
    "XeniumSlide": (".io", "XeniumSlide"),
    "DEFAULT_BOUNDARY_PROGRAM_LIBRARY": (".multimodal", "DEFAULT_BOUNDARY_PROGRAM_LIBRARY"),
    "DEFAULT_LAZYSLIDE_TEXT_TERMS": (".multimodal", "DEFAULT_LAZYSLIDE_TEXT_TERMS"),
    "DEFAULT_STRUCTURE_RNA_MARKERS": (".multimodal", "DEFAULT_STRUCTURE_RNA_MARKERS"),
    "ContourGmiConfig": (".gmi", "ContourGmiConfig"),
    "ContourGmiDataset": (".gmi", "ContourGmiDataset"),
    "ContourGmiResult": (".gmi", "ContourGmiResult"),
    "GmiModuleConfig": (".gmi", "GmiModuleConfig"),
    "GmiModuleResult": (".gmi", "GmiModuleResult"),
    "AxisStrengthConfig": (".mechanostress", "AxisStrengthConfig"),
    "MechanostressCohortResult": (".mechanostress", "MechanostressCohortResult"),
    "MechanostressConfig": (".mechanostress", "MechanostressConfig"),
    "MechanostressResult": (".mechanostress", "MechanostressResult"),
    "PolarityConfig": (".mechanostress", "PolarityConfig"),
    "SpatialPerturbBridgeConfig": (".perturb", "SpatialPerturbBridgeConfig"),
    "TumorStromaGrowthConfig": (".mechanostress", "TumorStromaGrowthConfig"),
    "HistoSegLazySlideConfig": (".multimodal", "HistoSegLazySlideConfig"),
    "add_contours_from_geojson": (".contour", "add_contours_from_geojson"),
    "import_histoseg_segmentation_qc": (".contour", "import_histoseg_segmentation_qc"),
    "build_contour_gmi_dataset": (".gmi", "build_contour_gmi_dataset"),
    "build_gmi_effect_graph": (".gmi", "build_gmi_effect_graph"),
    "build_contour_feature_table": (".contour", "build_contour_feature_table"),
    "build_atera_slides": (".io", "build_atera_slides"),
    "build_10x_public_slides": (".io", "build_10x_public_slides"),
    "classify_tumor_stroma_growth": (".mechanostress", "classify_tumor_stroma_growth"),
    "expand_contours": (".contour", "expand_contours"),
    "aggregate_multi_sample_study": (".multimodal", "aggregate_multi_sample_study"),
    "aggregate_structure_image_features": (".multimodal", "aggregate_structure_image_features"),
    "annotate_joint_cell_states": (".multimodal", "annotate_joint_cell_states"),
    "assign_tiles_to_histoseg_structures": (".multimodal", "assign_tiles_to_histoseg_structures"),
    "build_cohort_handoff_spec": (".multimodal", "build_cohort_handoff_spec"),
    "build_panel_gap_table": (".multimodal", "build_panel_gap_table"),
    "build_serializable_pilot_summary": (".multimodal", "build_serializable_pilot_summary"),
    "build_spatial_niches": (".multimodal", "build_spatial_niches"),
    "build_summary": (".multimodal", "build_summary"),
    "build_spatho_manifest": (".multimodal", "build_spatho_manifest"),
    "build_spatialperturb_handoff": (".perturb", "build_spatialperturb_handoff"),
    "build_top_hypotheses_table": (".multimodal", "build_top_hypotheses_table"),
    "build_xenium_slide": (".io", "build_xenium_slide"),
    "compute_pathway_activity_matrix": (".pathway", "compute_pathway_activity_matrix"),
    "discover_gmi_modules": (".gmi", "discover_gmi_modules"),
    "discover_10x_xenium_datasets": (".io", "discover_10x_xenium_datasets"),
    "compute_ane_density": (".mechanostress", "compute_ane_density"),
    "compute_cell_polarity": (".mechanostress", "compute_cell_polarity"),
    "compute_distance_expression_coupling": (".mechanostress", "compute_distance_expression_coupling"),
    "compute_rna_protein_discordance": (".multimodal", "compute_rna_protein_discordance"),
    "compare_programs_with_embeddings": (".multimodal", "compare_programs_with_embeddings"),
    "estimate_cell_axes": (".mechanostress", "estimate_cell_axes"),
    "extract_ranked_patches": (".multimodal", "extract_ranked_patches"),
    "export_for_stgpt": (".multimodal", "export_for_stgpt"),
    "histoseg_contours_to_image_table": (".multimodal", "histoseg_contours_to_image_table"),
    "generate_missing_contours_with_histoseg": (".io", "generate_missing_contours_with_histoseg"),
    "cci_topology_analysis": (".cci", "cci_topology_analysis"),
    "load_anndata_from_partial": (".io", "load_anndata_from_partial"),
    "import_stgpt_embeddings": (".multimodal", "import_stgpt_embeddings"),
    "load_rna_protein_anndata": (".multimodal", "load_rna_protein_anndata"),
    "load_xenium_gene_protein": (".io", "load_xenium_gene_protein"),
    "pathway_topology_analysis": (".pathway", "pathway_topology_analysis"),
    "plot_auc_heatmap": (".multimodal", "plot_auc_heatmap"),
    "plot_DE_volcano": (".multimodal", "plot_DE_volcano"),
    "plot_model_diagnostics": (".multimodal", "plot_model_diagnostics"),
    "plot_topk_per_cluster": (".multimodal", "plot_topk_per_cluster"),
    "protein_gene_correlation": (".multimodal", "protein_gene_correlation"),
    "read_slide": (".io", "read_slide"),
    "read_xenium": (".io", "read_xenium"),
    "read_xenium_slide": (".io", "read_xenium_slide"),
    "resolve_10x_dataset_metadata": (".io", "resolve_10x_dataset_metadata"),
    "render_contour_boundary_ecology_report": (".multimodal", "render_contour_boundary_ecology_report"),
    "render_contour_gmi_report": (".gmi", "render_contour_gmi_report"),
    "render_gmi_module_report": (".gmi", "render_gmi_module_report"),
    "render_mechanostress_report": (".mechanostress", "render_mechanostress_report"),
    "render_markdown_report": (".multimodal", "render_markdown_report"),
    "render_renal_immune_resistance_report": (".multimodal", "render_renal_immune_resistance_report"),
    "ring_density": (".contour", "ring_density"),
    "rna_protein_cluster_analysis": (".multimodal", "rna_protein_cluster_analysis"),
    "run_contour_boundary_ecology_pilot": (".multimodal", "run_contour_boundary_ecology_pilot"),
    "run_histoseg_lazyslide_structure_workflow": (".multimodal", "run_histoseg_lazyslide_structure_workflow"),
    "run_contour_gmi": (".gmi", "run_contour_gmi"),
    "run_atera_breast_contour_gmi": (".gmi", "run_atera_breast_contour_gmi"),
    "run_mechanostress_cohort": (".mechanostress", "run_mechanostress_cohort"),
    "run_mechanostress_workflow": (".mechanostress", "run_mechanostress_workflow"),
    "run_renal_immune_resistance_pilot": (".multimodal", "run_renal_immune_resistance_pilot"),
    "run_validated_renal_ffpe_smoke": (".multimodal", "run_validated_renal_ffpe_smoke"),
    "score_contour_boundary_programs": (".multimodal", "score_contour_boundary_programs"),
    "score_gmi_modules": (".gmi", "score_gmi_modules"),
    "select_primary_contour_geojson": (".io", "select_primary_contour_geojson"),
    "score_immune_resistance_program": (".multimodal", "score_immune_resistance_program"),
    "smooth_density_by_distance": (".contour", "smooth_density_by_distance"),
    "spatialperturb_status": (".perturb", "spatialperturb_status"),
    "summarize_axial_orientation": (".mechanostress", "summarize_axial_orientation"),
    "summarize_cell_polarity": (".mechanostress", "summarize_cell_polarity"),
    "summarize_tumor_growth": (".mechanostress", "summarize_tumor_growth"),
    "validate_summary": (".multimodal", "validate_summary"),
    "validate_hnscc_mechanostress_outputs": (".mechanostress", "validate_hnscc_mechanostress_outputs"),
    "validate_suzuki_luad_mechanostress_outputs": (".mechanostress", "validate_suzuki_luad_mechanostress_outputs"),
    "write_contour_boundary_ecology_artifacts": (".multimodal", "write_contour_boundary_ecology_artifacts"),
    "write_mechanostress_artifacts": (".mechanostress", "write_mechanostress_artifacts"),
    "write_model_scores": (".multimodal", "write_model_scores"),
    "write_output_artifacts": (".multimodal", "write_output_artifacts"),
    "write_spatialperturb_handoff": (".perturb", "write_spatialperturb_handoff"),
    "write_renal_immune_resistance_artifacts": (".multimodal", "write_renal_immune_resistance_artifacts"),
    "write_slide": (".io", "write_slide"),
    "write_xenium": (".io", "write_xenium"),
    "write_xenium_slide": (".io", "write_xenium_slide"),
}


def __getattr__(name: str):
    if name in _MODULE_EXPORTS:
        value = import_module(_MODULE_EXPORTS[name], __name__)
        globals()[name] = value
        return value
    if name in _ATTRIBUTE_EXPORTS:
        module_name, attribute_name = _ATTRIBUTE_EXPORTS[name]
        module = import_module(module_name, __name__)
        value = getattr(module, attribute_name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_MODULE_EXPORTS) | set(_ATTRIBUTE_EXPORTS))


__all__ = [
    "__version__",
    "PUBLIC_DATASET_SOURCES",
    "ProteinMicroEnv",
    "ProteinModelResult",
    "XeniumSlide",
    "DEFAULT_BOUNDARY_PROGRAM_LIBRARY",
    "DEFAULT_LAZYSLIDE_TEXT_TERMS",
    "DEFAULT_STRUCTURE_RNA_MARKERS",
    "ContourGmiConfig",
    "ContourGmiDataset",
    "ContourGmiResult",
    "GmiModuleConfig",
    "GmiModuleResult",
    "AxisStrengthConfig",
    "MechanostressCohortResult",
    "MechanostressConfig",
    "MechanostressResult",
    "PolarityConfig",
    "SpatialPerturbBridgeConfig",
    "TumorStromaGrowthConfig",
    "HistoSegLazySlideConfig",
    "add_contours_from_geojson",
    "import_histoseg_segmentation_qc",
    "build_contour_gmi_dataset",
    "build_gmi_effect_graph",
    "build_contour_feature_table",
    "build_atera_slides",
    "build_10x_public_slides",
    "classify_tumor_stroma_growth",
    "expand_contours",
    "aggregate_multi_sample_study",
    "aggregate_structure_image_features",
    "annotate_joint_cell_states",
    "assign_tiles_to_histoseg_structures",
    "build_cohort_handoff_spec",
    "build_panel_gap_table",
    "build_serializable_pilot_summary",
    "build_spatial_niches",
    "build_spatialperturb_handoff",
    "build_spatho_manifest",
    "build_summary",
    "build_top_hypotheses_table",
    "build_xenium_slide",
    "benchmarking",
    "compute_ane_density",
    "compute_cell_polarity",
    "compute_distance_expression_coupling",
    "compute_pathway_activity_matrix",
    "discover_gmi_modules",
    "discover_10x_xenium_datasets",
    "compute_rna_protein_discordance",
    "compare_programs_with_embeddings",
    "contour",
    "extract_ranked_patches",
    "export_for_stgpt",
    "histoseg_contours_to_image_table",
    "estimate_cell_axes",
    "generate_missing_contours_with_histoseg",
    "get_public_dataset_sources",
    "gmi",
    "io",
    "cci_topology_analysis",
    "cci",
    "mechanostress",
    "import_stgpt_embeddings",
    "load_anndata_from_partial",
    "load_rna_protein_anndata",
    "load_xenium_gene_protein",
    "multimodal",
    "pathway_topology_analysis",
    "pathway",
    "perturb",
    "plot_auc_heatmap",
    "plot_DE_volcano",
    "plot_model_diagnostics",
    "plot_topk_per_cluster",
    "protein_gene_correlation",
    "read_slide",
    "read_xenium",
    "read_xenium_slide",
    "resolve_10x_dataset_metadata",
    "render_contour_boundary_ecology_report",
    "render_contour_gmi_report",
    "render_gmi_module_report",
    "render_mechanostress_report",
    "ring_density",
    "render_markdown_report",
    "render_renal_immune_resistance_report",
    "rna_protein_cluster_analysis",
    "run_contour_boundary_ecology_pilot",
    "run_histoseg_lazyslide_structure_workflow",
    "run_contour_gmi",
    "run_atera_breast_contour_gmi",
    "run_mechanostress_cohort",
    "run_mechanostress_workflow",
    "run_renal_immune_resistance_pilot",
    "run_validated_renal_ffpe_smoke",
    "score_contour_boundary_programs",
    "score_gmi_modules",
    "select_primary_contour_geojson",
    "score_immune_resistance_program",
    "smooth_density_by_distance",
    "spatialperturb_status",
    "summarize_axial_orientation",
    "summarize_cell_polarity",
    "summarize_tumor_growth",
    "validate_hnscc_mechanostress_outputs",
    "validate_suzuki_luad_mechanostress_outputs",
    "validate_summary",
    "validation",
    "write_contour_boundary_ecology_artifacts",
    "write_mechanostress_artifacts",
    "write_model_scores",
    "write_output_artifacts",
    "write_spatialperturb_handoff",
    "write_renal_immune_resistance_artifacts",
    "write_slide",
    "write_xenium",
    "write_xenium_slide",
]
