version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .                   # 安装你的包（src 布局也可以）
    - requirements: docs/requirements.txt
