site_name: pyXenium
site_description: "A lightweight Python toolkit for loading and analyzing 10x Xenium data (RNA + Protein)."
site_url: https://pyxenium.readthedocs.io/
repo_url: https://github.com/hutaobo/pyXenium
repo_name: hutaobo/pyXenium
copyright: "© 2025 pyXenium contributors"
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Guides:
      - Xenium data loading: guides/xenium-data-loading.md
      - Protein–Gene correlation: guides/protein-gene-correlation.md
  - API Reference:
      - analysis.protein_gene_correlation: api/analysis_protein_gene_correlation.md
      - Full package index: api/index.md
  - Changelog: changelog.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            group_by_category: true
            members_order: source
            show_source: true
            separate_signature: true
            show_signature_annotations: true
            filters:
              - "!^_"
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hutaobo/pyXenium
watch:
  - src/pyXenium
  - docs
