[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyXenium"
version = "0.1.2"
description = "Tools for reading and analyzing 10x Xenium data"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [{ name = "Taobo Hu", email = "taobo.hu@dbb.su.se" }]
dependencies = [
  "anndata>=0.10",
  "click>=8.1",
  "matplotlib>=3.8",
  "numpy>=1.24",
  "pandas>=2.0",
  "scikit-learn>=1.3",
  "scipy>=1.10",
  "tqdm>=4.66",
  "zarr>=2.16",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["pyXenium*"]

[tool.setuptools.package-data]
pyXenium = ["data/**", "*.csv", "*.zarr", "*.txt"]

[project.scripts]
pyxenium-import-partial = "pyXenium.io.partial_xenium_loader:app"
