[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyXenium"
version = "0.2.0"
description = "A toy Python package for analyzing 10x Xenium data."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [{ name = "Taobo Hu" }]

# 运行时依赖（按你项目真实需要填写；示例）
dependencies = [
  "anndata>=0.10",
  "numpy>=1.23",
  "pandas>=2.0",
  "scipy>=1.10",
  "scikit-learn>=1.3",
  "zarr>=3.1",
  "fsspec>=2024.6.0",
  "requests>=2.31",
]

[project.optional-dependencies]
# ★ 新增：CI 里用到的 .[dev]（pytest、构建/发布、文档等常见开发依赖）
dev = [
  "pytest>=7",
  "pytest-cov",
  "build",
  "twine",
  "mkdocs",
  "mkdocs-material",
]

[tool.setuptools]
# ★ 明确 src 布局
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["pyXenium*"]
