# pyXenium/config/protein_aliases.yaml
# 规范名（你的数据列名）: [同义词、基因名、变体写法...]
PD-1:         [PD1, PDCD1]
VISTA:        [VSIR]
PD-L1:        [PDL1, CD274]
LAG-3:        [LAG3]
CD16:         [FCGR3A, FCGR3B]
GranzymeB:    [GZMB, GRANZYMEB]
CD163:        [CD163]
CD4:          [CD4]
CD20:         [MS4A1]
CD8A:         [CD8A]
CD3E:         [CD3E]
CD138:        [SDC1]
HLA-DR:       [HLADR, HLA-DRA, HLA-DRB1]
CD11c:        [ITGAX, CD11C]
CD68:         [CD68]
CD45RA:       [CD45-RA, PTPRC-RA]
PCNA:         [PCNA]
CD45RO:       [CD45-RO, PTPRC-RO]
Ki-67:        [KI67, MKI67, Ki67]
Beta-catenin: [BETACATENIN, CTNNB1, BetaCatenin, β-catenin]
CD31:         [PECAM1]
PTEN:         [PTEN]
PanCK:        [PANCK, KRT8, KRT18, KRT19, Pan-CK, CK-pan]
Vimentin:     [VIM]
alphaSMA:     [ACTA2, ALPHASMA, αSMA, aSMA]
CD45:         [PTPRC]
E-Cadherin:   [ECADHERIN, CDH1, E-cadherin]
