from __future__ import annotations

from ._a100 import (
    DEFAULT_GMI_A100_READONLY_XENIUM_ROOT,
    DEFAULT_GMI_A100_REMOTE_ROOT,
    build_gmi_a100_plan,
    validate_a100_gmi_path_policy,
    write_gmi_a100_plan,
)
from ._pdc import (
    DEFAULT_GMI_PDC_CONTOUR_GEOJSON,
    DEFAULT_GMI_PDC_HISTOSEG_ROOT,
    DEFAULT_GMI_PDC_ROOT,
    DEFAULT_GMI_PDC_REQUIRED_DATASET_FILES,
    DEFAULT_GMI_PDC_XENIUM_ROOT,
    build_gmi_pdc_plan,
    summarize_gmi_pdc_runs,
    validate_pdc_gmi_path_policy,
    write_gmi_pdc_plan,
)
from ._dataset import (
    build_contour_gmi_dataset,
    build_spatial_gmi_dataset,
    build_within_label_heterogeneity_dataset,
    compute_contour_heterogeneity,
    shuffle_spatial_feature_block,
    write_contour_gmi_dataset,
    write_spatial_gmi_dataset,
)
from ._runner import build_gmi_install_command, check_r_packages, ensure_vendored_gmi_installed
from ._types import (
    ContourGmiConfig,
    ContourGmiDataset,
    ContourGmiResult,
    SpatialGmiConfig,
    SpatialGmiDataset,
    SpatialGmiResult,
)
from ._vendor import assert_vendored_gmi_complete, get_vendored_gmi_metadata, get_vendored_gmi_path
from ._workflow import (
    DEFAULT_ATERA_CONTOUR_GEOJSON,
    load_atera_breast_for_gmi,
    render_contour_gmi_report,
    render_spatial_gmi_report,
    run_atera_breast_contour_gmi,
    run_atera_breast_gmi,
    run_contour_gmi,
    run_spatial_gmi,
)

__all__ = [
    "DEFAULT_ATERA_CONTOUR_GEOJSON",
    "DEFAULT_GMI_A100_READONLY_XENIUM_ROOT",
    "DEFAULT_GMI_A100_REMOTE_ROOT",
    "DEFAULT_GMI_PDC_CONTOUR_GEOJSON",
    "DEFAULT_GMI_PDC_HISTOSEG_ROOT",
    "DEFAULT_GMI_PDC_ROOT",
    "DEFAULT_GMI_PDC_REQUIRED_DATASET_FILES",
    "DEFAULT_GMI_PDC_XENIUM_ROOT",
    "ContourGmiConfig",
    "ContourGmiDataset",
    "ContourGmiResult",
    "SpatialGmiConfig",
    "SpatialGmiDataset",
    "SpatialGmiResult",
    "assert_vendored_gmi_complete",
    "build_contour_gmi_dataset",
    "build_gmi_a100_plan",
    "build_gmi_install_command",
    "build_gmi_pdc_plan",
    "build_spatial_gmi_dataset",
    "build_within_label_heterogeneity_dataset",
    "check_r_packages",
    "compute_contour_heterogeneity",
    "ensure_vendored_gmi_installed",
    "get_vendored_gmi_metadata",
    "get_vendored_gmi_path",
    "load_atera_breast_for_gmi",
    "render_contour_gmi_report",
    "render_spatial_gmi_report",
    "run_atera_breast_contour_gmi",
    "run_atera_breast_gmi",
    "run_contour_gmi",
    "run_spatial_gmi",
    "shuffle_spatial_feature_block",
    "summarize_gmi_pdc_runs",
    "validate_a100_gmi_path_policy",
    "validate_pdc_gmi_path_policy",
    "write_gmi_a100_plan",
    "write_gmi_pdc_plan",
    "write_contour_gmi_dataset",
    "write_spatial_gmi_dataset",
]
